DROP TABLE IF EXISTS signatures;

CREATE TABLE signatures (
	id SERIAL PRIMARY KEY,
	-- first VARCHAR NOT NULL CHECK(first != ''),
	-- last VARCHAR NOT NULL CHECK(last != ''),
	signature VARCHAR NOT NULL CHECK(signature != ''),
	userID INTEGER NOT NULL REFERENCES users(userID) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
